services:
  - type: web
    name: clear-connect-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: clear-connect-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false

