services:
  - type: web
    name: clear-connect-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true

  - type: web
    name: clear-connect-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true

